// "Manuale" dell'app per l'assistente "Chiedi a Fornelli". Ogni voce ha parole
// chiave, una risposta scritta (così niente invenzioni) e un'azione facoltativa
// (apri la pagina/funzione giusta). L'AI sceglie SOLO tra questi id: non inventa.
//
// action.type: "page" (vai a una scheda) | "open" (apri una finestra/strumento) | "tour" (passi guidati)
export const HELP_TOPICS = [
  { id: "casa-condivisa", title: "Condividere la lista della spesa", kw: "condividere condivisa casa insieme stessa lista federica marito moglie altro telefono sincronizzata coppia", answer: "Sì! In Impostazioni → \"Casa condivisa\" crei una casa e ottieni un codice; l'altra persona entra con lo stesso codice (col suo accesso). Da quel momento avete la STESSA lista della spesa, aggiornata in tempo reale, con avviso quando l'altro aggiunge qualcosa.", action: { type: "open", target: "household" }, tour: "casa" },
  { id: "modalita-cucina", title: "Cucinare passo-passo (Modalità cucina)", kw: "cucinare passo passi modalita cucina guidata timer voce mani libere leggi ad alta voce ingredienti toccabili", answer: "Apri una ricetta e tocca \"Cucina\" nella barra in basso: istruzioni una alla volta, più timer con nome, lettura a voce e schermo sempre acceso. Col microfono 🎤 vai avanti/indietro a voce, avvii timer e puoi anche fare domande (\"posso sostituire il burro?\"). Tocca un ingrediente nel passo per vedere la quantità.", action: { type: "page", target: "strumenti" } },
  { id: "import-video", title: "Importare una ricetta da un video social", kw: "video social tiktok instagram youtube reel importare link", answer: "Apri \"Nuova ricetta\" → \"Importa da video social\": incolla il link di TikTok/Instagram/YouTube e l'AI ne ricava ingredienti e passi. Se il link non basta, incolla la descrizione del video.", action: { type: "open", target: "nuova-ricetta" } },
  { id: "inventa-ricetta", title: "Inventare una ricetta dagli ingredienti", kw: "inventare inventa creare ricetta dagli ingredienti che ho ai genera", answer: "In \"Nuova ricetta\", in cima sotto \"Non hai voglia di scrivere?\", tocca \"Inventa (AI)\": scrivi gli ingredienti che hai e l'app propone una ricetta da modificare e salvare.", action: { type: "open", target: "nuova-ricetta" } },
  { id: "adatta-ricetta", title: "Rendere una ricetta vegana / leggera / senza glutine", kw: "vegano vegetariano senza glutine senza lattosio leggera adattare dieta convertire trasformare", answer: "Apri la ricetta e tocca \"Adatta la ricetta\": scegli vegano, vegetariano, senza glutine, senza lattosio o più leggera. L'AI la riscrive e la salvi come nuova ricetta (l'originale resta).", action: { type: "page", target: "strumenti" } },
  { id: "foto-frigo", title: "Sapere cosa cucinare dal frigo (foto)", kw: "frigo frigorifero foto fotografa dispensa cosa cucino ingredienti che ho riconosce", answer: "In Spesa → scheda \"Dispensa\" tocca \"Fotografa il frigo\": l'AI riconosce gli alimenti dalla foto e puoi aggiungerli in dispensa o cercare ricette.", action: { type: "page", target: "spesa-dispensa" }, tour: "frigo" },
  { id: "robot", title: "Adattare una ricetta al Companion o al Bimby", kw: "companion moulinex bimby robot cuociture velocita temperatura programma", answer: "Apri una ricetta e tocca \"Modalità robot\": scegli Companion o Bimby e l'AI traduce la ricetta nei comandi (accessorio, velocità, temperatura, tempo) da impostare a mano sul robot.", action: { type: "page", target: "strumenti" } },
  { id: "menu-settimana", title: "Pianificare il menù della settimana", kw: "menu settimana pianificare piano calendario cene pranzi pasti programmare ai", answer: "Vai in Piano → vista Settimana. Tocca \"Crea il menù\" e scegli: con l'assistente (ti fa vedere la proposta prima di confermare), in automatico dalle tue preferite (prepara anche la spesa) o a caso. Da lì generi anche la spesa della settimana.", action: { type: "page", target: "piano" }, tour: "menusett" },
  { id: "timer", title: "Usare più timer da cucina", kw: "timer cronometro minuti contaminuti sveglia più timer", answer: "Apri Impostazioni → \"Timer da cucina\": avvii più timer con nome (pasta, forno…) che continuano a contare mentre usi l'app e suonano alla fine.", action: { type: "open", target: "timer" } },
  { id: "aggiungi-ricetta", title: "Aggiungere una ricetta", kw: "aggiungere nuova ricetta inserire salvare creare scrivere", answer: "Tocca \"Nuova ricetta\" nella schermata Ricette. In cima, sotto \"Non hai voglia di scrivere?\", ci sono tre scorciatoie: \"Fotografa\", \"Detta a voce\" e \"Inventa (AI)\". Più sotto puoi incollare un link e toccare \"Importa ingredienti dal link\", o importarla da un video social.", action: { type: "open", target: "nuova-ricetta" } },
  { id: "detta-ricetta", title: "Dettare una ricetta a voce", kw: "dettare detta voce microfono parlare raccontare scrivere senza mani nonna telefonata", answer: "In \"Nuova ricetta\", in cima sotto \"Non hai voglia di scrivere?\", tocca \"Detta a voce\": racconti la ricetta al telefono e l'app la trascrive e la divide in ingredienti e passi. Utile mentre te la fanno dettare al telefono. Serve il microfono e la connessione.", action: { type: "open", target: "nuova-ricetta" } },
  { id: "ocr-foto", title: "Leggere una ricetta da un libro/foto", kw: "libro quaderno foto scansionare ocr leggere carta scritta", answer: "In \"Nuova ricetta\", in cima sotto \"Non hai voglia di scrivere?\", tocca \"Fotografa\": l'app legge il testo (ingredienti o preparazione) da una foto di un libro o quaderno.", action: { type: "open", target: "nuova-ricetta" } },
  { id: "cerca-online", title: "Cercare ricette online (anche per robot)", kw: "cercare online scopri ricettario fonti idee giallozafferano misya moulinex bimby trovare ispirazione", answer: "Vai in Scopri → \"Cerca online\". Scrivi un piatto e scegli la fonte; con \"Tutte le fonti\" vedi tutti i risultati. Scrivendo il nome di una fonte o robot (es. \"pollo bimby\") cerca solo lì.", action: { type: "page", target: "ricettario" } },
  { id: "dispensa-scadenze", title: "Dispensa e avvisi di scadenza", kw: "dispensa scadenza scade alimenti avvisi anti spreco usa prima scorte correggere cambiare data", answer: "In Spesa → \"Dispensa\" metti ciò che hai in casa con la scadenza: l'app ti avvisa prima che scada e in Home suggerisce ricette per consumarlo. Tocca la data (o \"+ scad.\") su una riga per metterla o correggerla: pastiglie da 3 giorni, 1 settimana, 1 mese, 6 mesi, oppure la data esatta. Tocca la ⭐ per le scorte di base.", action: { type: "page", target: "spesa-dispensa" } },
  { id: "budget", title: "Tenere d'occhio la spesa (budget)", kw: "budget spesa soldi costo mensile quanto spendo tetto", answer: "In Spesa → \"Da comprare\", tocca la riga della spesa del mese per impostare un budget mensile: vedrai una barra con quanto hai speso.", action: { type: "page", target: "spesa" } },
  { id: "supermercato", title: "Fare la spesa più veloce al supermercato (Modalità supermercato)", kw: "supermercato spesa negozio corsie schermo intero grande veloce mani piene carrello", answer: "In Spesa → \"Da comprare\" tocca \"Modalità supermercato\": la lista occupa tutto lo schermo, con articoli grandi ordinati per reparto (come giri tra le corsie) e una barra che mostra quanto manca. Comoda con le mani occupate dal carrello.", action: { type: "page", target: "spesa" } },
  { id: "preferenze-diete", title: "Impostare preferenze alimentari e porzioni", kw: "preferenze vegetariano senza glutine senza lattosio porzioni predefinite per me dieta impostazioni cucina", answer: "In Impostazioni → \"Preferenze di cucina\" trovi vegetariano, senza glutine, senza lattosio: in Home appare il filtro \"Per me\" e le ricette non adatte si nascondono. Nella stessa sezione imposti anche le porzioni predefinite.", action: { type: "page", target: "impostazioni" } },
  { id: "notifiche", title: "Attivare i promemoria/notifiche", kw: "notifiche promemoria avvisi push ricordare scadenze pasti", answer: "In Impostazioni attiva \"Promemoria\": ricevi avvisi per scadenze e pasti del giorno (anche ad app chiusa). Puoi scegliere l'ora.", action: { type: "page", target: "impostazioni" } },
  { id: "aspetto", title: "Cambiare aspetto (tema, colore, testo)", kw: "tema chiaro scuro colore accento testo grande dimensione aspetto contrasto personalizzare home", answer: "In Impostazioni scegli tema chiaro/scuro, colore dell'app, dimensione del testo, alto contrasto e quali sezioni mostrare in Home.", action: { type: "page", target: "impostazioni" } },
  { id: "teglia", title: "Adattare le dosi a una teglia diversa", kw: "teglia stampo dimensione tortiera dosi ricalcolare rotonda quadrata", answer: "Apri una ricetta con le porzioni e tocca \"Adatta alla teglia/stampo\": inserisci la teglia della ricetta e la tua e ricalcolo le dosi in base alla superficie.", action: { type: "page", target: "strumenti" } },
  { id: "backup", title: "Salvare/esportare le ricette (backup)", kw: "backup esporta importa salva copia perdere dati ripristino pdf", answer: "In Impostazioni: \"Esporta backup\" salva tutte le ricette in un file, \"Importa backup\" le ripristina. Con l'accesso cloud sono già salvate e sincronizzate. Puoi anche esportare un PDF.", action: { type: "page", target: "impostazioni" } },
  { id: "torna-comera", title: "Annullare un ripristino sbagliato (Torna com'era)", kw: "ripristino sbagliato annulla torna comera backup automatico copia sicurezza sbagliato errore rimettere a posto", answer: "L'app fa da sola, una volta al giorno, una copia di sicurezza silenziosa, e ne fa un'altra proprio prima di ogni \"Importa backup\". Se un ripristino va storto, in Impostazioni → \"Torna com'era\" rimetti tutto come stava prima, senza dover ritrovare un vecchio file. Se il telefono ha la memoria piena, l'app avvisa e non procede senza questa rete di sicurezza.", action: { type: "page", target: "impostazioni" } },
  { id: "scontrino", title: "Scansionare lo scontrino della spesa", kw: "scontrino scansiona spesa fatta scanner ocr ricevuta scarica dispensa foto", answer: "In Spesa → \"Dispensa\" tocca \"Scansiona lo scontrino\": fotografi lo scontrino, l'app legge il testo direttamente sul telefono e mette gli alimenti in dispensa, senza scriverli a mano.", action: { type: "page", target: "spesa-dispensa" } },
  { id: "come-lo-imposto", title: "Sapere come impostare forno, microonde, friggitrice o piano cottura", kw: "forno microonde friggitrice aria piano cottura come impostare temperatura gradi ripiano preriscaldare watt", answer: "Apri una ricetta con lo strumento giusto (forno, microonde, friggitrice ad aria o piano cottura, con il modello scelto nello strumento) e tocca \"Come lo imposto?\": l'app suggerisce funzione, temperatura o potenza, ripiano, preriscaldamento e come capire che è pronto. Se in una ricetta il pulsante non c'è, è normale: compare solo per gli strumenti che hanno qualcosa da impostare, e non per pentola a pressione, wok, planetaria o tostapane.", action: { type: "page", target: "strumenti" } },
  { id: "conservazione", title: "Quanto dura un piatto, e quando è cotto dentro", kw: "conservazione scadenza frigo congelatore quanto dura quanti giorni temperatura al cuore cotto dentro sicurezza alimentare termometro", answer: "Apri una ricetta: se c'è, trovi la scheda \"Quanto dura, e quando è cotto\" con quanti giorni si conserva in frigo, quanti mesi in congelatore, e per le carni la temperatura al cuore (da misurare con un termometro da cucina). Sono valori da fonti verificate sulla sicurezza alimentare, non inventati dall'AI — ma restano indicazioni prudenti: se qualcosa ti sembra strano, fidati dei tuoi sensi.", action: { type: "page", target: "strumenti" } },
  { id: "porziona-congela", title: "Congelare gli avanzi con un'etichetta (Porziona e congela)", kw: "congelare congelatore porziona etichetta avanzi scadenza freezer consumato", answer: "Apri una ricetta e tocca \"Porziona e congela\": crei un'etichetta per il congelatore con piatto, porzioni, data e \"da consumare entro\". In Spesa → Dispensa → \"Congelatore\" trovi il conto alla rovescia e tocchi \"Consumato\" quando lo usi.", action: { type: "page", target: "spesa-dispensa" } },
  { id: "presto-ricomprare", title: "Sapere cosa sta per finire (Presto da ricomprare)", kw: "presto ricomprare finire scorte predittivo abitudini restock", answer: "In Spesa → \"Dispensa\" trovi \"Presto da ricomprare\": l'app impara da sola, con l'uso, ogni quanto ricompri un alimento e ti avvisa quando probabilmente sta per finire; con un tocco lo aggiungi alla spesa. All'inizio è vuoto, si riempie piano piano.", action: { type: "page", target: "spesa-dispensa" } },
  { id: "svuota-frigo", title: "Smaltire gli avanzi prima che scadano (Svuota il frigo)", kw: "svuota frigo avanzi anti spreco scadenza consumare ricette con quello che ho", answer: "In Spesa → \"Dispensa\" tocca \"Cosa posso cucinare con questi?\" e poi \"Oppure scegli gli avanzi dalla dispensa\": scegli gli alimenti da consumare (quelli in scadenza sono già spuntati) e l'app cerca le tue ricette che li usano, oppure te ne inventa una con l'AI.", action: { type: "page", target: "spesa-dispensa" } },
  { id: "bilancio-settimana", title: "Vedere il bilancio nutrizionale della settimana", kw: "bilancio nutrizionale settimana calorie proteine carboidrati grassi equilibrio macronutrienti", answer: "Vai in Piano → vista Settimana: se hai calcolato i valori nutrizionali di qualche pasto pianificato, tocca il riquadro in fondo per il \"Bilancio della settimana\" con le calorie per giorno e la ripartizione di proteine, carboidrati e grassi. È una stima, non un dato preciso.", action: { type: "page", target: "piano" } },
  { id: "sfide-settimana", title: "Le sfide della settimana", kw: "sfide settimana obiettivi missioni lunedì mini obiettivi", answer: "In Home tocca il riquadro \"Sfide\": ogni lunedì l'app propone 3 mini-obiettivi (una ricetta di stagione, una ricetta nuova, anti-spreco…) con una barra di avanzamento. Sono diverse dai Traguardi, che restano fissi per sempre.", action: { type: "page", target: "strumenti" } },
  { id: "album-cucina", title: "Sfogliare l'album di cucina", kw: "album cucina foto ricordi diario timeline piatti cucinati", answer: "In Impostazioni → \"I tuoi numeri\" tocca \"Sfoglia l'album di cucina\": una linea del tempo con le foto di tutto ciò che hai cucinato, raggruppata per mese, come un album di ricordi. (Trovi lo stesso album anche da Impostazioni → \"Diario di cucina\" → \"Album\".)", action: { type: "page", target: "impostazioni" } },
  { id: "aggiungi-calendario", title: "Aggiungere i pasti al calendario del telefono", kw: "calendario telefono promemoria pasti aggiungi evento ics", answer: "In Piano tocca un giorno e poi \"Aggiungi al calendario\": mette i pasti nel calendario del telefono (iPhone o Android) con un promemoria 2 ore prima.", action: { type: "page", target: "piano" } },
  { id: "muro-ricette", title: "Vedere tutte le ricette con foto (Muro delle ricette)", kw: "muro ricette galleria foto mosaico tutte le ricette", answer: "In Home, quando hai almeno 4 ricette con foto, compare il riquadro \"Muro\": una galleria a mosaico di tutte le ricette con foto, da scorrere e toccare per aprirle.", action: { type: "page", target: "strumenti" } },
  { id: "reazioni-famiglia", title: "Lasciare una reazione a un piatto (reazioni della famiglia)", kw: "reazioni famiglia emoji piaciuto voto rapido cuore fuoco pollice", answer: "In una ricetta trovi \"Reazioni della famiglia\": ognuno (col proprio nickname) lascia una reazione rapida (😍🔥👍😐) su come gli è piaciuto un piatto.", action: { type: "page", target: "strumenti" } },
  { id: "copertina-personale", title: "Mettere una tua foto in cima alla Home (Copertina personale)", kw: "copertina personale foto home saluto personalizzare immagine", answer: "In Impostazioni → \"Copertina personale\" scegli una tua foto (un piatto del cuore, un ricordo) da mettere in cima alla Home, con il saluto e \"Il ricettario di …\".", action: { type: "page", target: "impostazioni" } }
];

// Normalizza (minuscole, niente accenti) per un confronto tollerante.
function norm(s) {
  return (s || "").toLowerCase().normalize("NFD").replace(/[̀-ͯ]/g, "").replace(/[^a-z0-9\s]/g, " ");
}
// Ricerca fuzzy semplice: punteggio per parole in comune con titolo+keyword+risposta.
export function findHelpTopics(query, limit = 4) {
  const words = norm(query).split(/\s+/).filter((w) => w.length >= 3);
  if (!words.length) return [];
  const STOP = new Set(["come", "posso", "fare", "puoi", "voglio", "che", "cosa", "per", "con", "una", "uno", "del", "della", "fornelli", "app", "dove", "quando", "serve", "faccio"]);
  const terms = words.filter((w) => !STOP.has(w));
  if (!terms.length) return [];
  const scored = HELP_TOPICS.map((t) => {
    const hay = norm(t.title + " " + t.kw + " " + t.answer);
    const titleKw = norm(t.title + " " + t.kw);
    let s = 0;
    for (const w of terms) {
      if (titleKw.includes(w)) s += 3;
      else if (hay.includes(w)) s += 1;
    }
    return { t, s };
  }).filter((x) => x.s > 0).sort((a, b) => b.s - a.s);
  return scored.slice(0, limit).map((x) => x.t);
}
